### ISSUE TITLE
Format of ANE name

### ISSUE THREAD

**Issue by giralt** [ietf-wg-alto/draft-ietf-alto-unified-props-new#1]

**Comment by giralt** [comment]
https://mailarchive.ietf.org/arch/msg/alto/O73kZUhbSkKYrplcLfNDgS_QYps/

**Comment by emiapwil** [comment]
Final decision: follow option 1

See [here](https://mailarchive.ietf.org/arch/msg/alto/J4_UpjvrLkJPIRLan9Yjw4Xw6y4/) for the conversation.
